### ISSUE TITLE
Not relaying broadcast 255.255.255.255 across vlans

### ISSUE THREAD

**Issue by Joeviocoe** [marjohn56/udpbroadcastrelay#9]
Running pfsense 2.6.0-RELEASE (amd64)
built on Mon Jan 31 19:57:53 UTC 2022
FreeBSD 12.3-STABLE

Have a WeatherFlow Tempest hub:
`tcpdump -vvnn -i re1.900 udp port 50222`
> tcpdump: listening on re1.900, link-type EN10MB (Ethernet), capture size 262144 bytes
> 01:32:52.978060 IP (tos 0x0, ttl 255, id 3629, offset 0, flags [none], proto UDP (17), length 127)
>     10.0.9.22.50222 > 255.255.255.255.50222: [udp sum ok] UDP, length 99

`udpbroadcastrelay --id 42 --port 50222 --dev re1.900 --dev re1.10 -d -f`
> ID set to 42
> Port set to 50222
> Forking Mode enabled
> ID: 42 (DSCP: 42, ToS: 0xa8), Port 50222
> re1.900: 15 / 10.0.9.1 / 10.0.9.63
> re1.10: 17 / 10.0.0.65 / 10.0.0.127
> found 2 interfaces total
> Done Initializing

I can verify the process is still running.  But not sure how to verify it properly binds to the udp port or if it needs to since this is broadcast, and not multicast.

The issue is...
`tcpdump -vvnn -i re1.10 udp port 50222`
returns nothing.

**Comment by remkolems** [comment]
I had the exact same issue. 

pfSense+
22.05-RELEASE (amd64)
built on Wed Jun 22 18:56:13 UTC 2022
FreeBSD 12.3-STABLE

Weatherflow hub (AIR and SKY)

pfSense shell -> cmd:
`/usr/bin/nohup /usr/local/sbin/udpbroadcastrelay --id 50222 --port 50222 --dev ixl0 --dev ixl0.30`

Result:
![image](https://user-images.githubusercontent.com/45675902/192100012-4d22b2f8-d8b9-4ff6-b7d2-4d6993da940a.png)

`ixl0     `== Home Assistant (192.168.2.x
`ixl0.30 `== Weatherflow Hub (on a VLAN: 192.168.30.x)
`broadcast `== 255.255.255.255 (of ixl0.30) and 192.168.2.255 (of ixl0). The latter will disappear if udpbroadcastrelay is not running properly (my own assessment/deduction) 

I use Home Assistant to establish a connection to the Weatherflow hub. Therefore I added a pfSense firewall rule on the network where Weatherflow is residing to allow communication with Home Assistant. Under advanced options of that rule tick: **Allow IP options** (utmost important!).

pfSense pfTop result:
![image](https://user-images.githubusercontent.com/45675902/192099939-2a353aae-ed71-4c3a-a42e-e97399f2874d.png)

The DIR(ection) **In** and **Out** are important on 192.168.2.255 considering **Age** factor.

I do/did verify the connection from Home Assistant. Example given:
![image](https://user-images.githubusercontent.com/45675902/192100378-f3e28d9c-06ef-4d1d-ba97-b1362148d3a1.png)

Notice: "6 seconds ago" versus the **DIR** "In" and "Out" and **Age**.

**Comment by Joeviocoe** [comment]
So you got it working just by adding a rule with "Allow IP options" enabled?
Nice.

I got impatient and just used tcpdump and netcat.

```
#!/usr/local/bin/bash

while true
	do tcpdump -vvnnAA -s0 -c1 -i <WeatherFlow_Interface> udp port 50222 2>/dev/null | grep -Eo '\{".*\}' | ncat -u <HA_IP> 50222
done
```
